# -*- coding: utf-8 -*-
"""Computer Vision.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZkPbHeVmgBwXJnmaJZnN4Iw35RtZW0sw
"""

!pip install medmnist torch torchvision scikit-learn seaborn matplotlib -q
import importlib, sys

if "medmnist" not in sys.modules:
    import subprocess
    subprocess.run(["pip", "install", "medmnist", "-q"], check=True)

import importlib
importlib.invalidate_caches()

import numpy as np
import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import DataLoader, TensorDataset
from torchvision import transforms, models
from medmnist import PneumoniaMNIST
import matplotlib.pyplot as plt
from sklearn.metrics import roc_auc_score, classification_report, confusion_matrix
import seaborn as sns
import warnings
warnings.filterwarnings("ignore")

DEVICE = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(f"Using device: {DEVICE}")

BATCH_SIZE = 64
NUM_EPOCHS_CNN = 20
NUM_EPOCHS_MBN = 15
LR = 1e-3
IMG_SIZE_CNN = 28
IMG_SIZE_MBN = 224

def get_loaders_cnn():
    tf = transforms.Compose([
        transforms.ToTensor(),
        transforms.Normalize(mean=[0.5], std=[0.5])
    ])
    train = PneumoniaMNIST(split="train", transform=tf, download=True)
    val   = PneumoniaMNIST(split="val",   transform=tf, download=True)
    test  = PneumoniaMNIST(split="test",  transform=tf, download=True)
    return (
        DataLoader(train, batch_size=BATCH_SIZE, shuffle=True,  num_workers=2),
        DataLoader(val,   batch_size=BATCH_SIZE, shuffle=False, num_workers=2),
        DataLoader(test,  batch_size=BATCH_SIZE, shuffle=False, num_workers=2),
    )

def get_loaders_mobilenet():
    tf_train = transforms.Compose([
        transforms.Resize((IMG_SIZE_MBN, IMG_SIZE_MBN)),
        transforms.Grayscale(num_output_channels=3),
        transforms.RandomHorizontalFlip(),
        transforms.RandomRotation(10),
        transforms.ToTensor(),
        transforms.Normalize([0.485, 0.456, 0.406], [0.229, 0.224, 0.225]),
    ])
    tf_eval = transforms.Compose([
        transforms.Resize((IMG_SIZE_MBN, IMG_SIZE_MBN)),
        transforms.Grayscale(num_output_channels=3),
        transforms.ToTensor(),
        transforms.Normalize([0.485, 0.456, 0.406], [0.229, 0.224, 0.225]),
    ])
    train = PneumoniaMNIST(split="train", transform=tf_train, download=True)
    val   = PneumoniaMNIST(split="val",   transform=tf_eval,  download=True)
    test  = PneumoniaMNIST(split="test",  transform=tf_eval,  download=True)
    return (
        DataLoader(train, batch_size=32,  shuffle=True,  num_workers=2),
        DataLoader(val,   batch_size=32,  shuffle=False, num_workers=2),
        DataLoader(test,  batch_size=32,  shuffle=False, num_workers=2),
    )

class PneumoniaCNN(nn.Module):
    def __init__(self):
        super().__init__()
        self.features = nn.Sequential(
            nn.Conv2d(1, 32, kernel_size=3, padding=1),
            nn.BatchNorm2d(32),
            nn.ReLU(),
            nn.MaxPool2d(2),                          # 14x14

            nn.Conv2d(32, 64, kernel_size=3, padding=1),
            nn.BatchNorm2d(64),
            nn.ReLU(),
            nn.MaxPool2d(2),                          # 7x7

            nn.Conv2d(64, 128, kernel_size=3, padding=1),
            nn.BatchNorm2d(128),
            nn.ReLU(),
            nn.AdaptiveAvgPool2d((3, 3)),             # 3x3
        )
        self.classifier = nn.Sequential(
            nn.Flatten(),
            nn.Linear(128 * 3 * 3, 256),
            nn.ReLU(),
            nn.Dropout(0.4),
            nn.Linear(256, 1),
        )

    def forward(self, x):
        return self.classifier(self.features(x))


def build_mobilenet():
    model = models.mobilenet_v2(weights=models.MobileNet_V2_Weights.IMAGENET1K_V1)
    for param in model.parameters():
        param.requires_grad = False
    # unfreeze last 3 blocks + classifier
    for layer in list(model.features.children())[-3:]:
        for param in layer.parameters():
            param.requires_grad = True
    model.classifier = nn.Sequential(
        nn.Dropout(0.3),
        nn.Linear(model.last_channel, 1),
    )
    return model

def train_epoch(model, loader, optimizer, criterion):
    model.train()
    total_loss, correct, n = 0.0, 0, 0
    for x, y in loader:
        x, y = x.to(DEVICE), y.float().to(DEVICE)
        optimizer.zero_grad()
        out = model(x).squeeze(1)
        loss = criterion(out, y.squeeze(1))
        loss.backward()
        optimizer.step()
        total_loss += loss.item() * x.size(0)
        preds = (torch.sigmoid(out) > 0.5).float()
        correct += (preds == y.squeeze(1)).sum().item()
        n += x.size(0)
    return total_loss / n, correct / n


@torch.no_grad()
def evaluate(model, loader, criterion):
    model.eval()
    total_loss, correct, n = 0.0, 0, 0
    all_probs, all_labels = [], []
    for x, y in loader:
        x, y = x.to(DEVICE), y.float().to(DEVICE)
        out = model(x).squeeze(1)
        loss = criterion(out, y.squeeze(1))
        total_loss += loss.item() * x.size(0)
        probs = torch.sigmoid(out)
        preds = (probs > 0.5).float()
        correct += (preds == y.squeeze(1)).sum().item()
        n += x.size(0)
        all_probs.extend(probs.cpu().numpy())
        all_labels.extend(y.squeeze(1).cpu().numpy())
    auc = roc_auc_score(all_labels, all_probs)
    return total_loss / n, correct / n, auc, all_probs, all_labels


def run_training(model, train_loader, val_loader, optimizer, scheduler, n_epochs, label):
    criterion = nn.BCEWithLogitsLoss()
    history = {"train_loss": [], "val_loss": [], "train_acc": [], "val_acc": [], "val_auc": []}

    best_auc, best_weights = 0.0, None

    for epoch in range(1, n_epochs + 1):
        tr_loss, tr_acc = train_epoch(model, train_loader, optimizer, criterion)
        vl_loss, vl_acc, vl_auc, _, _ = evaluate(model, val_loader, criterion)
        scheduler.step(vl_loss)

        history["train_loss"].append(tr_loss)
        history["val_loss"].append(vl_loss)
        history["train_acc"].append(tr_acc)
        history["val_acc"].append(vl_acc)
        history["val_auc"].append(vl_auc)

        if vl_auc > best_auc:
            best_auc = vl_auc
            best_weights = {k: v.clone() for k, v in model.state_dict().items()}

        print(f"[{label}] Epoch {epoch:02d}/{n_epochs} | "
              f"train loss: {tr_loss:.4f} acc: {tr_acc:.4f} | "
              f"val loss: {vl_loss:.4f} acc: {vl_acc:.4f} auc: {vl_auc:.4f}")

    model.load_state_dict(best_weights)
    return history

train_cnn, val_cnn, test_cnn = get_loaders_cnn()

cnn = PneumoniaCNN().to(DEVICE)
opt_cnn = optim.Adam(cnn.parameters(), lr=LR, weight_decay=1e-4)
sch_cnn = optim.lr_scheduler.ReduceLROnPlateau(opt_cnn, patience=3, factor=0.5)

history_cnn = run_training(cnn, train_cnn, val_cnn, opt_cnn, sch_cnn, NUM_EPOCHS_CNN, "CNN")

criterion = nn.BCEWithLogitsLoss()
_, test_acc_cnn, test_auc_cnn, cnn_probs, cnn_labels = evaluate(cnn, test_cnn, criterion)
print(f"\nCNN Test Accuracy: {test_acc_cnn:.4f} | AUC: {test_auc_cnn:.4f}")

train_mbn, val_mbn, test_mbn = get_loaders_mobilenet()

mbn = build_mobilenet().to(DEVICE)
opt_mbn = optim.Adam(filter(lambda p: p.requires_grad, mbn.parameters()), lr=3e-4, weight_decay=1e-4)
sch_mbn = optim.lr_scheduler.ReduceLROnPlateau(opt_mbn, patience=3, factor=0.5)

history_mbn = run_training(mbn, train_mbn, val_mbn, opt_mbn, sch_mbn, NUM_EPOCHS_MBN, "MobileNetV2")

_, test_acc_mbn, test_auc_mbn, mbn_probs, mbn_labels = evaluate(mbn, test_mbn, criterion)
print(f"\nMobileNetV2 Test Accuracy: {test_acc_mbn:.4f} | AUC: {test_auc_mbn:.4f}")

fig, axes = plt.subplots(2, 3, figsize=(18, 10))
fig.suptitle("PneumoniaMNIST: Custom CNN vs MobileNetV2", fontsize=14, fontweight="bold")

# Loss curves
for i, (hist, name, color) in enumerate(zip(
    [history_cnn, history_mbn], ["CNN", "MobileNetV2"], ["steelblue", "darkorange"]
)):
    axes[i][0].plot(hist["train_loss"], label="train", color=color)
    axes[i][0].plot(hist["val_loss"],   label="val",   color=color, linestyle="--")
    axes[i][0].set_title(f"{name} — Loss")
    axes[i][0].set_xlabel("Epoch")
    axes[i][0].legend()

    axes[i][1].plot(hist["train_acc"], label="train", color=color)
    axes[i][1].plot(hist["val_acc"],   label="val",   color=color, linestyle="--")
    axes[i][1].set_title(f"{name} — Accuracy")
    axes[i][1].set_xlabel("Epoch")
    axes[i][1].legend()

    probs  = cnn_probs  if i == 0 else mbn_probs
    labels = cnn_labels if i == 0 else mbn_labels
    preds  = (np.array(probs) > 0.5).astype(int)
    cm = confusion_matrix(labels, preds)
    sns.heatmap(cm, annot=True, fmt="d", cmap="Blues", ax=axes[i][2],
                xticklabels=["Normal", "Pneumonia"],
                yticklabels=["Normal", "Pneumonia"])
    axes[i][2].set_title(f"{name} — Confusion Matrix")
    axes[i][2].set_ylabel("True")
    axes[i][2].set_xlabel("Predicted")

plt.tight_layout()
plt.savefig("results.png", dpi=150)
plt.show()

print("\n" + "=" * 50)
print(f"{'Model':<20} {'Test Acc':>10} {'Test AUC':>10}")
print("-" * 50)
print(f"{'Custom CNN':<20} {test_acc_cnn:>10.4f} {test_auc_cnn:>10.4f}")
print(f"{'MobileNetV2':<20} {test_acc_mbn:>10.4f} {test_auc_mbn:>10.4f}")
print("=" * 50)

print("\nCustom CNN — Classification Report:")
print(classification_report(cnn_labels, (np.array(cnn_probs) > 0.5).astype(int),
                             target_names=["Normal", "Pneumonia"]))

print("MobileNetV2 — Classification Report:")
print(classification_report(mbn_labels, (np.array(mbn_probs) > 0.5).astype(int),
                             target_names=["Normal", "Pneumonia"]))

# save models
torch.save(cnn.state_dict(), "cnn_pneumonia.pth")
torch.save(mbn.state_dict(), "mobilenetv2_pneumonia.pth")

from sklearn.metrics import roc_curve

fpr, tpr, thresholds = roc_curve(cnn_labels, cnn_probs)
optimal_idx = np.argmax(tpr - fpr)
optimal_threshold = thresholds[optimal_idx]
print(f"Optimal threshold: {optimal_threshold:.3f}")

preds_adjusted = (np.array(cnn_probs) > optimal_threshold).astype(int)
print(classification_report(cnn_labels, preds_adjusted, target_names=["Normal", "Pneumonia"]))